Repository Alt-Org/Altzone-Server, pull requests merged in 2024-08, with the labels that each got.

#93 Create test.txt
  src/clan/test.txt
Labels: feature

#98 Add @FormatResponse()
  src/authorization/caslAbility.factory.ts
  src/characterClass/characterClass.controller.ts
  src/common/base/decorator/AddType.decorator.ts
  src/common/controller/APIError.ts
  src/common/controller/APIErrorReason.ts
  src/common/controller/formatResponse.ts
  src/common/decorator/response/FormatAPIResponse.ts
  src/common/service/basicService/BasicService.ts
  src/common/service/basicService/IService.ts
  src/common/service/basicService/SEReason.ts
  src/common/service/basicService/ServiceError.ts
Labels: feature

#94 add BasicService class
  src/authorization/caslAbility.factory.ts
  src/characterClass/characterClass.controller.ts
  src/common/base/decorator/AddType.decorator.ts
  src/common/service/basicService/BasicService.ts
  src/common/service/basicService/IService.ts
  src/common/service/basicService/SEReason.ts
  src/common/service/basicService/ServiceError.ts
Labels: feature

#103 add examples
  src/authorization/authorization.interceptor.ts
  src/authorization/caslAbility.factory.ts
  src/authorization/decorator/Authorize.ts
  src/authorization/rule/characterClassRules.ts
  src/characterClass/characterClass.controller.ts
  src/characterClass/characterClass.module.ts
  src/characterClass/characterClass.schema.ts
  src/characterClass/characterClass.service.ts
  src/characterClass/decorator/validation/IsCharacterClassExists.decorator.ts
  src/characterClass/dto/characterClass.dto.ts
  src/characterClass/dto/createCharacterClass.dto.ts
  src/characterClass/dto/updateCharacterClass.dto.ts
  src/common/base/decorator/AddBasicService.decorator.ts
  src/common/base/decorator/AddType.decorator.ts
  src/common/decorator/param/GetAllQuery.ts
  src/common/decorator/request/AddGetQueries.decorator.ts
  src/common/decorator/response/ValidationExceptionFilter.ts
  src/common/interceptor/request/addSearchQuery.interceptor.ts
  src/common/interceptor/request/offsetPagination.interceptor.ts
  src/common/interceptor/response/Serialize.ts
Labels: docs

#105 fix bug with @AddType() overriding object fields
  src/authorization/authorization.interceptor.ts
  src/characterClass/characterClass.controller.ts
  src/common/service/basicService/BasicService.ts
Labels: bug

#114 update swagger
  doc/img/ERD.png
  swagger/swagger.json
Labels: docs

#125 Fix bug with /player GET and /chat GET
  src/authorization/rule/playerRules.ts
  src/chat/chat.controller.ts
  src/common/interceptor/request/offsetPagination.interceptor.ts
Labels: bug

#136 fix bug with playerCount field in Clan collection
  src/app.module.ts
  src/authorization/caslAbility.factory.ts
  src/authorization/rule/clanRules.ts
  src/authorization/rule/joinRequestRules.ts
  src/clan/clan.controller.ts
  src/clan/clan.counters.ts
  src/clan/clan.module.ts
  src/clan/clan.schema.ts
  src/clan/clan.service.ts
  src/clan/defaultValues/soulHome.ts
  src/clan/defaultValues/stock.ts
  src/clan/join/dto/playerLeave.dto.ts
  src/clan/join/join.controller.ts
  src/clan/join/join.module.ts
  src/clan/join/join.service.ts
  src/clan/test.txt
  src/common/service/counter/Counter.ts
  src/common/service/counter/ICounter.ts
  src/common/service/counter/ICounterFactory.ts
Labels: bug

#140 Create test.txt
  src/clan/test.txt
Labels: feature

#138 Change basic implementation for room enpoint to meet new requirements
  src/Room/dto/createRoom.dto.ts
  src/Room/dto/room.dto.ts
  src/Room/dto/updateRoom.dto.ts
  src/Room/room.controller.ts
  src/Room/room.module.ts
  src/Room/room.schema.ts
  src/Room/room.service.ts
  src/Room/utils/room.helper.service.ts
  src/app.module.ts
  src/authorization/caslAbility.factory.ts
  src/authorization/rule/roomRules.ts
  src/clan/clan.module.ts
  src/clan/clan.service.ts
  src/clan/defaultValues/soulHome.ts
  src/clan/dto/clan.dto.ts
  src/clan/join/join.service.ts
  src/item/dto/item.dto.ts
  src/item/item.schema.ts
  src/shop/clanVote/clanVote.controller.ts
  src/soulhome/soulhome.module.ts
  src/soulhome/soulhome.service.ts
Labels: change

#142 mark files as deprecated
  src/common/base/abstract/basicAndConditionServiceDummy.abstract.ts
  src/common/base/abstract/basicServiceDummy.abstract.ts
  src/common/base/abstract/conditionServiceDummy.abstract.ts
  src/common/base/decorator/AddConditionService.decorator.ts
  src/common/base/decorator/BasicDELETE.decorator.ts
  src/common/base/decorator/BasicGET.decorator.ts
  src/common/base/decorator/BasicPOST.decorator.ts
  src/common/base/decorator/BasicPUT.decorator.ts
  src/common/base/decorator/ThrowNotImplementedMethod.decorator.ts
  src/common/decorator/response/CatchCreateUpdateErrors.ts
  src/common/decorator/response/ThrowResponseErrorIfFound.ts
  src/common/decorator/response/responseType.ts
  src/common/enum/apiObjectName.enum.ts
  src/common/enum/discriminator.enum.ts
  src/common/enum/stockType.enum.ts
  src/common/interceptor/request/addMetaDataQuery.interceptor.ts
  src/common/interceptor/request/cursorPagination.interceptor.ts
  src/util/parser/IFieldParser.ts
  src/util/parser/fieldParser.ts
Labels: docs

#144 remove unused code
  src/common/base/abstract/basicAndConditionServiceDummy.abstract.ts
  src/common/base/abstract/conditionServiceDummy.abstract.ts
  src/common/base/decorator/AddConditionService.decorator.ts
  src/common/base/interface/IBasicAndConditionService.ts
  src/common/base/interface/IConditionService.ts
  src/common/enum/stockType.enum.ts
  src/common/interceptor/request/addMetaDataQuery.interceptor.ts
  src/common/interceptor/request/cursorPagination.interceptor.ts
  src/util/parser/IFieldParser.ts
  src/util/parser/fieldParser.ts
  src/util/parser/index.ts
Labels: change

#151 add LoggedUser decorator for controller methods PR
  src/characterClass/characterClass.controller.ts
  src/common/decorator/param/LoggedUser.decorator.ts
Labels: feature

#147 Add JSDocs for common package PR
  src/common/controller/APIErrorReason.ts
  src/common/dto/_id.dto.ts
  src/common/dto/getQuery.dto.ts
  src/common/enum/gestaltCycle.enum.ts
  src/common/enum/modelName.enum.ts
  src/common/function/addUniqueArrayElements.ts
  src/common/function/deleteArrayElements.ts
  src/common/function/deleteNotUniqueArrayElements.ts
  src/common/function/timeUtils.ts
  src/common/interceptor/request/addSearchQuery.interceptor.ts
  src/common/interceptor/request/addSortQuery.interceptor.ts
  src/common/interceptor/request/offsetPagination.interceptor.ts
  src/common/interceptor/response/Send204OnEmptyRes.ts
  src/common/interceptor/response/Serialize.ts
  src/common/interface/IClass.ts
  src/common/interface/IDiscriminator.ts
  src/common/interface/IGetAllQuery.ts
  src/common/interface/IHookImplementer.ts
  src/common/interface/IResponseShape.ts
  src/common/service/basicService/SEReason.ts
  src/common/service/basicService/ServiceError.ts
  src/common/service/counter/Counter.ts
  src/common/type/ignoreReferences.type.ts
  src/common/type/search.type.ts
Labels: docs

#149 add IncludeQuery decorator for controller methods parameters PR
  src/characterClass/characterClass.controller.ts
  src/characterClass/characterClass.schema.ts
  src/characterClass/characterClass.service.ts
  src/common/controller/APIError.ts
  src/common/decorator/param/IncludeQuery.decorator.ts
Labels: feature

#154 update swagger description PR
  swagger/swagger.json
Labels: docs

#156 Update all error responses to new form with APIError[] PR
  src/auth/auth.guard.ts
  src/auth/decorator/ThrowAuthErrorIfFound.decorator.ts
  src/authorization/authorization.interceptor.ts
  src/common/decorator/response/CatchCreateUpdateErrors.ts
  src/common/decorator/response/FormatAPIResponse.ts
  src/common/decorator/response/ThrowResponseErrorIfFound.ts
  src/common/decorator/response/UniformResponse.ts
  src/common/exceptionFilter/ValidationExceptionFilter.ts
  src/main.ts
Labels: feature

#157 Add room activation and deactivation logic PR
  doc/img/room_activation/room_activation.drawio
  doc/img/room_activation/room_activation.svg
  src/Room/dto/ActivateRoom.dto.ts
  src/Room/dto/createRoom.dto.ts
  src/Room/dto/updateRoom.dto.ts
  src/Room/room.controller.ts
  src/Room/room.module.ts
  src/Room/room.schema.ts
  src/Room/room.service.ts
  src/Room/utils/room.helper.service.ts
  src/soulhome/dto/soulhome.dto.ts
  swagger/swagger.json
Labels: feature
