Repository Alt-Org/Altzone-Server, pull requests merged in 2024-11, with the labels that each got.

#313 remove forwardRefs
  src/clan/clan.module.ts
  src/clanInventory/item/itemHelper.service.ts
  src/clanInventory/room/room.service.ts
  src/clanInventory/stock/stock.service.ts
  src/gameData/gameData.service.ts
  src/itemMover/itemMover.service.ts
  src/rewarder/playerRewarder/playerRewarder.service.ts
  src/rewarder/playerRewarder/points.ts
Labels: change, PR

#317 Tehtävän annon mukainen tiedosto
  src/characterClass/MikaR.txt
Labels: feature, PR

#318 Add tests for common controller folder
  src/test/common/controller/APIError/APIError.test.ts
  src/test/common/controller/APIError/convertToAPIError.test.ts
  src/test/common/controller/APIError/isAPIError.test.ts
  src/test/common/controller/formatResponse.test.ts
Labels: PR, test

#330 Feature/add flea market get endpoints 196
  src/app.module.ts
  src/common/enum/modelName.enum.ts
  src/fleaMarket/dto/fleaMarketItem.dto.ts
  src/fleaMarket/enum/status.enum.ts
  src/fleaMarket/fleaMarket.controller.ts
  src/fleaMarket/fleaMarket.module.ts
  src/fleaMarket/fleaMarket.service.ts
  src/fleaMarket/fleaMarketItem.schema.ts
Labels: feature, PR

#332 Fix bug with /playerTasks not returning tasks
  src/playerTasks/playerTasks.service.ts
Labels: bug, PR

#331 Make /leaderboard public
  src/leaderboard/leaderboard.controller.ts
  swagger/swagger.json
Labels: bug, PR

#337 add tests for profile service class
  package-lock.json
  package.json
  src/auth/auth.service.ts
  src/common/base/decorator/AddBasicService.decorator.ts
  src/common/service/envHandler/envVars.ts
  src/profile/profile.controller.ts
  src/profile/profile.schema.ts
  src/profile/profile.service.ts
  src/test/common/service/basicService/BasicService/BasicService.deleteOneById.test.ts
  src/test/common/service/basicService/BasicService/BasicService.updateOneById.test.ts
  src/test/common/service/counter/Counter/Counter.decrease.test.ts
  src/test/common/service/counter/Counter/Counter.decreaseById.test.ts
  src/test/common/service/counter/Counter/Counter.decreaseByIdOnOne.test.ts
  src/test/common/service/counter/Counter/Counter.decreaseOnOne.test.ts
  src/test/common/service/counter/Counter/Counter.increase.test.ts
  src/test/common/service/counter/Counter/Counter.increaseById.test.ts
  src/test/common/service/counter/Counter/Counter.increaseByIdOnOne.test.ts
  src/test/common/service/counter/Counter/Counter.increaseOnOne.test.ts
  src/test/player/data/player/createPlayerDtoBuilder.ts
  src/test/player/data/player/playerDtoBuilder.ts
  src/test/player/data/playerBuilderFactory.ts
  src/test/player/modules/player.module.ts
  src/test/player/modules/playerCommon.module.ts
  src/test/profile/ProfileService/createOne.test.ts
  src/test/profile/ProfileService/createWithHashedPassword.test.ts
  src/test/profile/ProfileService/deleteByCondition.test.ts
  src/test/profile/ProfileService/deleteOneById.test.ts
  src/test/profile/ProfileService/readAll.test.ts
  src/test/profile/ProfileService/readOneById.test.ts
  src/test/profile/ProfileService/readOneWithAllCollections.test.ts
  src/test/profile/ProfileService/readOneWithCollections.test.ts
  src/test/profile/ProfileService/updateOneById.test.ts
  src/test/profile/data/profile/createProfileDtoBuilder.ts
  src/test/profile/data/profile/profileBuilder.ts
  src/test/profile/data/profile/profileDtoBuilder.ts
  src/test/profile/data/profile/updateProfileDtoBuilder.ts
  src/test/profile/data/profileBuilderFactory.ts
  src/test/profile/modules/profile.module.ts
  src/test/profile/modules/profileCommon.module.ts
  src/test/test_utils/test/util/getNonExisting_id.test.ts
  src/test/test_utils/util/getNonExisting_id.ts
Labels: PR, test

#340 add alexei.txt file
  src/characterClass/files/alexei.txt
Labels: feature

#341 add tests for PlayerService class
  src/clanInventory/clanInventory.module.ts
  src/test/clan/data/clan/ClanBuilder.ts
  src/test/clan/data/clan/CreateClanDtoBuilder.ts
  src/test/clan/data/clan/UpdateClanDtoBuilder.ts
  src/test/clan/data/clan/join/JoinRequestDtoBuilder.ts
  src/test/clan/data/clan/join/RemovePlayerDtoBuilder.ts
  src/test/clan/data/clanBuilderFactory.ts
  src/test/clan/modules/clan.module.ts
  src/test/clan/modules/clanCommon.ts
  src/test/player/PlayerService/createOne.test.ts
  src/test/player/PlayerService/deleteByCondition.test.ts
  src/test/player/PlayerService/deleteOneById.test.ts
  src/test/player/PlayerService/getAll.test.ts
  src/test/player/PlayerService/getPlayerById.test.ts
  src/test/player/PlayerService/readAll.test.ts
  src/test/player/PlayerService/readOneById.test.ts
  src/test/player/PlayerService/readOneWithAllCollections.test.ts
  src/test/player/PlayerService/readOneWithCollections.test.ts
  src/test/player/PlayerService/updateOneById.test.ts
  src/test/player/PlayerService/updatePlayerById.test.ts
  src/test/player/data/player/gameStatisticsBuilder.ts
  src/test/player/data/player/playerBuilder.ts
  src/test/player/data/player/updatePlayerDtoBuilder.ts
  src/test/player/data/playerBuilderFactory.ts
  src/test/player/modules/playerCommon.module.ts
  src/test/test_utils/util/removeDBDefaultFields.ts
Labels: PR, test

#349 change/stock-soulhome-default-items-348
  src/clan/utils/defaultValues/items.ts
  src/clanInventory/item/const/itemProperties.ts
  src/clanInventory/item/enum/itemName.enum.ts
Labels: change, PR
