Repository Alt-Org/Altzone-Server, pull requests merged in 2024-09, with the labels that each got.

#160 add room deletion methods PR
  src/Room/room.module.ts
  src/Room/room.service.ts
  src/item/item.controller.ts
  src/item/item.service.ts
Labels: feature, PR

#161 Add SoulHome basic logic PR
  src/authorization/caslAbility.factory.ts
  src/authorization/rule/roomRules.ts
  src/authorization/rule/soulHomeRules.ts
  src/clan/clan.service.ts
  src/clan/defaultValues/soulHome.ts
  src/soulhome/dto/createSoulHome.dto.ts
  src/soulhome/dto/soulhome.dto.ts
  src/soulhome/dto/updateSoulHome.dto.ts
  src/soulhome/soulhome.controller.ts
  src/soulhome/soulhome.module.ts
  src/soulhome/soulhome.schema.ts
  src/soulhome/soulhome.service.ts
  src/soulhome/utils/soulHomeHelper.service.ts
Labels: change, PR

#167 Change BasicSerice methods to return tuple
  src/Room/room.controller.ts
  src/Room/room.schema.ts
  src/Room/room.service.ts
  src/Room/utils/room.helper.service.ts
  src/characterClass/characterClass.controller.ts
  src/clan/clan.controller.ts
  src/clan/clan.service.ts
  src/clan/utils/clanHelper.service.ts
  src/common/decorator/response/FormatAPIResponse.ts
  src/common/exceptionFilter/ValidationExceptionFilter.ts
  src/common/service/basicService/BasicService.ts
  src/common/service/basicService/IService.ts
  src/item/item.service.ts
  src/shop/itemShop/itemShop.service.ts
  src/soulhome/soulhome.controller.ts
  src/soulhome/utils/soulHomeHelper.service.ts
  src/stock/stock.controller.ts
  src/stock/stock.schema.ts
  src/stock/stock.service.ts
Labels: change

#170 Add test.txt file
  src/clan/test.txt
Labels: feature

#172 add swagger file of 03.09.24 release PR
  swagger/releases/03-09-24-release.json
Labels: docs, PR

#175 Change chat logic
  doc/img/ERD.png
  src/authorization/authorization.interceptor.ts
  src/authorization/caslAbility.factory.ts
  src/authorization/rule/chatRules.ts
  src/chat/chat.controller.ts
  src/player/dto/createPlayer.dto.ts
  src/player/dto/player.dto.ts
  src/player/dto/updatePlayer.dto.ts
  src/player/player.schema.ts
  swagger/swagger.json
Labels: change, PR

#181 add parental control info for Player
  src/authorization/rule/chatRules.ts
  src/authorization/rule/playerRules.ts
  src/chat/chat.controller.ts
  src/player/dto/createPlayer.dto.ts
  src/player/dto/player.dto.ts
  src/player/dto/updatePlayer.dto.ts
  src/player/player.schema.ts
  swagger/swagger.json
Labels: feature, PR

#183 add saving log files endpoint
  .gitignore
  package-lock.json
  package.json
  prod_docker-compose.yml
  src/app.module.ts
  src/gameAnalytics/FileValidation.filter.ts
  src/gameAnalytics/SecretHeader.decorator.ts
  src/gameAnalytics/gameAnalytics.controller.ts
  src/gameAnalytics/gameAnalytics.module.ts
  src/gameAnalytics/logFile.service.ts
  swagger/swagger.json
Labels: feature, PR

#188 Feature/battle result informing endpoint 122
  src/app.module.ts
  src/common/enum/modelName.enum.ts
  src/gameData/dto/battleResponse.dto.ts
  src/gameData/dto/battleResult.dto.ts
  src/gameData/dto/createGame.dto.ts
  src/gameData/dto/game.dto.ts
  src/gameData/dto/resultType.dto.ts
  src/gameData/enum/requestType.enum.ts
  src/gameData/game.schema.ts
  src/gameData/gameData.controller.ts
  src/gameData/gameData.module.ts
  src/gameData/gameData.service.ts
  src/room/room.module.ts
  src/room/room.service.ts
Labels: feature, PR

#190 Added niklas.txt to /src/characterClass/files
  src/characterClass/files/niklas.txt
Labels: feature, PR
