Repository Alt-Org/Altzone-Server, pull requests merged in 2024-10, with the labels that each got.

#211 Feature/item stealing 111
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/common/decorator/response/UniformResponse.ts
  src/common/exceptionFilter/APIErrorFilter.ts
  src/item/decorator/param/StealToken.decorator.ts
  src/item/dto/stealItems.dto.ts
  src/item/errors/playerId.errors.ts
  src/item/guards/StealToken.guard.ts
  src/item/item.controller.ts
  src/item/item.module.ts
  src/item/item.service.ts
  src/item/itemHelper.service.ts
  src/item/itemMover.service.ts
  src/item/type/stealToken.type.ts
Labels: feature, PR

#220 Feature/retrieve player tasks 203
  .gitignore
  nest-cli.json
  src/app.module.ts
  src/playerTasks/enum/taskName.enum.ts
  src/playerTasks/playerTasks.controller.ts
  src/playerTasks/playerTasks.json
  src/playerTasks/playerTasks.module.ts
  src/playerTasks/playerTasks.service.ts
  src/playerTasks/type/task.type.ts
  src/playerTasks/type/tasks.type.ts
  tsconfig.json
Labels: feature, PR

#221 add redis db to docker compose files
  docker-compose.yml
  prod_docker-compose.yml
Labels: feature, PR

#225 add creation of the battle id folder for log files
  src/gameAnalytics/SecretHeader.decorator.ts
  src/gameAnalytics/decorator/BattleIdHeader.decorator.ts
  src/gameAnalytics/decorator/SecretHeader.decorator.ts
  src/gameAnalytics/gameAnalytics.controller.ts
  src/gameAnalytics/logFile.service.ts
  swagger/swagger.json
Labels: change, PR

#238 add new required fields to Clan model
  src/clan/clan.schema.ts
  src/clan/dto/clan.dto.ts
  src/clan/dto/createClan.dto.ts
  src/clan/dto/updateClan.dto.ts
  src/clan/enum/ageRange.enum.ts
  src/clan/enum/goal.enum.ts
  src/common/enum/language.enum.ts
  swagger/swagger.json
Labels: change, PR

#240 Change/clan default items 233
  src/clan/defaultValues/items.ts
  src/clan/utils/defaultValues/items.ts
  src/item/const/itemProperties.ts
  src/item/dto/createItem.dto.ts
  src/item/dto/item.dto.ts
  src/item/dto/updateItem.dto.ts
  src/item/enum/itemName.enum.ts
  src/item/enum/qualityLevel.enum.ts
  src/item/enum/recycling.enum.ts
  src/item/item.schema.ts
  src/shop/itemShop/itemShop.service.ts
Labels: change, PR

#244 Add MQTT broker setup
  docker-compose.yml
  mosquitto/config/aclfile.conf
  mosquitto/config/mosquitto.conf
  mosquitto/config/password_1
  nginx.conf
  prod_docker-compose.yml
Labels: feature, PR

#245 add env handler class
  src/app.module.ts
  src/common/service/envHandler/envHandler.ts
  src/common/service/envHandler/envVars.ts
  src/gameAnalytics/logFile.service.ts
  src/main.ts
Labels: feature, PR

#249 Make battle id header optional logfile while saving log file
  src/gameAnalytics/decorator/BattleIdHeader.decorator.ts
  src/gameAnalytics/gameAnalytics.controller.ts
  src/gameAnalytics/logFile.service.ts
  swagger/swagger.json
Labels: change, PR

#250 add notifications sending logic
  docker-compose.yml
  mosquitto/config/mosquitto.conf
  package-lock.json
  package.json
  src/common/service/notificator/MQTTConnector.ts
  src/common/service/notificator/NotificationSender.ts
  src/common/service/notificator/enum/NotificationGroup.enum.ts
  src/common/service/notificator/enum/NotificationResource.enum.ts
  src/common/service/notificator/enum/NotificationStatus.enum.ts
  src/playerTasks/playerTask.notifier.ts
Labels: feature, PR

#254 Feature/add played battles task 204
  src/common/enum/modelName.enum.ts
  src/gameData/gameData.module.ts
  src/gameData/gameData.service.ts
  src/playerTasks/dto/createTask.dto.ts
  src/playerTasks/enum/taskFrequency.enum.ts
  src/playerTasks/playerTasks.json
  src/playerTasks/playerTasks.module.ts
  src/playerTasks/playerTasks.schema.ts
  src/playerTasks/playerTasks.service.ts
Labels: feature, PR

#256 Add call to taskService to track won battles
  src/gameData/gameData.service.ts
  src/playerTasks/playerTasks.service.ts
Labels: feature, PR

#260 Feature/add won battles reward 209
  src/gameData/gameData.service.ts
  src/player/player.service.ts
Labels: feature, PR

#262 Feature/add sent chat messages task 206
  src/chat/chat.controller.ts
  src/chat/chat.module.ts
  src/chat/chat.service.ts
Labels: feature, PR

#285 add tests for BasicService class
  jest.config.js
  src/test/common/service/basicService/BasicService/BasicService.createMany.test.ts
  src/test/common/service/basicService/BasicService/BasicService.createOne.test.ts
  src/test/common/service/basicService/BasicService/BasicService.deleteMany.test.ts
  src/test/common/service/basicService/BasicService/BasicService.deleteOne.test.ts
  src/test/common/service/basicService/BasicService/BasicService.deleteOneById.test.ts
  src/test/common/service/basicService/BasicService/BasicService.readMany.test.ts
  src/test/common/service/basicService/BasicService/BasicService.readOne.test.ts
  src/test/common/service/basicService/BasicService/BasicService.readOneById.test.ts
  src/test/common/service/basicService/BasicService/BasicService.updateMany.test.ts
  src/test/common/service/basicService/BasicService/BasicService.updateOne.test.ts
  src/test/common/service/basicService/BasicService/BasicService.updateOneById.test.ts
  src/test/common/service/basicService/BasicService/BasicService_convertMongooseToServiceErrors.test.ts
  src/test/test_utils/add-custom-matchers.ts
  src/test/test_utils/const/loggedUser.ts
  src/test/test_utils/test/util/getNonExisting_id.test.ts
  src/test/test_utils/util/getNonExisting_id.ts
Labels: PR, test

#288 add tests for EnvHandler class
  src/test/clan_module/data/clan/ClanBuilder.ts
  src/test/clan_module/data/factory.ts
  src/test/common/service/counter/Counter/Counter.decrease.test.ts
  src/test/common/service/counter/Counter/Counter.decreaseById.test.ts
  src/test/common/service/counter/Counter/Counter.decreaseByIdOnOne.test.ts
  src/test/common/service/counter/Counter/Counter.decreaseOnOne.test.ts
  src/test/common/service/counter/Counter/Counter.increase.test.ts
  src/test/common/service/counter/Counter/Counter.increaseById.test.ts
  src/test/common/service/counter/Counter/Counter.increaseByIdOnOne.test.ts
  src/test/common/service/counter/Counter/Counter.increaseOnOne.test.ts
  src/test/common/service/envHandler/EnvHandler/EnvHandler.validateAllEnvFound.test.ts
Labels: PR, test

#292 add tests for NotificationSender class
  src/test/common/service/notificator/MQTTConnector/MQTTConnector.connect.test.ts
  src/test/common/service/notificator/MQTTConnector/MQTTConnector.disconnect.test.ts
  src/test/common/service/notificator/MQTTConnector/MQTTConnector.getInstance.test.ts
  src/test/common/service/notificator/MQTTConnector/MQTTConnector.publish.test.ts
  src/test/common/service/notificator/NotificationSender/NotificationSender.buildNotification.test.ts
Labels: PR, test

#294 add test for AddSortQueryInterceptor class
  src/common/interceptor/request/addSearchQuery.interceptor.ts
  src/common/interceptor/request/addSortQuery.interceptor.ts
  src/test/common/interceptor/request/AddSearchQueryInterceptor/AddSearchQueryInterceptor.test.ts
  src/test/common/interceptor/request/AddSearchQueryInterceptor/AddSortQueryInterceptor.test.ts
  src/test/test_utils/data/BodyBuilder.ts
  src/test/test_utils/data/CallHandlerBuilder.ts
  src/test/test_utils/data/ExecutionContextBuilder.ts
  src/test/test_utils/data/RequestBuilder.ts
  src/test/test_utils/data/TestUtilsDataFactory.ts
Labels: PR, test

#296 add tests for SerializeInterceptor class
  src/common/interceptor/response/Send204OnEmptyRes.ts
  src/common/interceptor/response/Serialize.ts
  src/test/common/interceptor/response/Send204OnEmptyResInterceptor/Send204OnEmptyResInterceptor.test.ts
  src/test/common/interceptor/response/SerializeInterceptor/SerializeInterceptor.test.ts
Labels: PR, test

#300 add tests for ValidationExceptionFilter class
  src/test/common/exceptionFilter/ValidationExceptionFilter/ValidationExceptionFilter.catch.test.ts
  src/test/common/exceptionFilter/ValidationExceptionFilter/ValidationExceptionFilter.validationToAPIErrors.test.ts
  src/test/test_utils/data/BadRequestExceptionBuilder.ts
  src/test/test_utils/data/TestUtilsDataFactory.ts
  src/test/test_utils/data/ValidationErrorBuilder.ts
Labels: PR, test

#298 Feature/add sent messages reward 208
  src/authorization/rule/playerRules.ts
  src/chat/chat.module.ts
  src/chat/chat.service.ts
  src/player/dto/gameStatistics.dto.ts
  src/player/dto/player.dto.ts
  src/player/gameStatistics.schema.ts
  src/player/message.schema.ts
  src/player/player.service.ts
Labels: feature, PR

#309 add tests for ExtractField() decorator
  src/test/common/decorator/response/ExtractField.test.ts
  src/test/common/decorator/response/FormatAPIResponse.test.ts
  src/test/common/decorator/response/UniformResponse.test.ts
Labels: PR, test

#307 add tests for UniformResponse decorator
  src/test/common/decorator/response/UniformResponse.test.ts
Labels: PR, test
