Repository Alt-Org/Altzone-Server, pull requests merged in 2025-02, with the labels that each got.

#397 add tests for @IsCustomCharacterExists()
  src/__tests__/player/customCharacter/decorator/validation/IsCustomCharacterExists/IsCustomCharacterExists.test.ts
Labels: PR, test

#395 Add item PUT endpoint
  src/__tests__/clanInventory/data/item/updateItemDtoBuilder.ts
  src/__tests__/clanInventory/item/ItemService/updateOneById.test.ts
  src/authorization/rule/itemRules.ts
  src/clanInventory/item/dto/createItem.dto.ts
  src/clanInventory/item/dto/updateItem.dto.ts
  src/clanInventory/item/item.controller.ts
Labels: feature, PR

#409 Add tests for auth module
  src/__tests__/auth/AuthService/signIn.test.ts
  src/__tests__/auth/AuthService/verifyToken.test.ts
  src/__tests__/auth/decorator/AuthGuard/canActivate.test.ts
  src/__tests__/auth/decorator/ThrowAuthErrorIfFound.test.ts
  src/__tests__/auth/modules/auth.module.ts
  src/__tests__/auth/modules/authCommonModule.ts
  src/auth/auth.service.ts
Labels: PR, test

#412 add tests for item mover module
  .gitignore
  package.json
  sonar_docker-compose.yml
  src/__tests__/itemMover/ItemMoverService/moveItem.test.ts
  src/__tests__/itemMover/ItemMoverService/moveItems.test.ts
  src/__tests__/itemMover/ItemMoverService/stealItems.test.ts
  src/__tests__/itemMover/modules/itemMover.module.ts
  src/__tests__/itemMover/modules/itemMoverCommon.module.ts
  src/itemMover/itemMover.service.ts
Labels: PR, test

#411 Milestone/change player tasks to daily tasks
  src/app.module.ts
  src/clan/clan.module.ts
  src/clan/clan.service.ts
  src/common/enum/modelName.enum.ts
  src/dailyTasks/consts/taskConstants.ts
  src/dailyTasks/dailyTask.notifier.ts
  src/dailyTasks/dailyTask.queue.ts
  src/dailyTasks/dailyTasks.controller.ts
  src/dailyTasks/dailyTasks.module.ts
  src/dailyTasks/dailyTasks.schema.ts
  src/dailyTasks/dailyTasks.service.ts
  src/dailyTasks/dto/dailyTask.dto.ts
  src/dailyTasks/enum/taskName.enum.ts
  src/dailyTasks/errors/taskReserved.error.ts
  src/dailyTasks/taskGenerator.service.ts
  src/dailyTasks/type/task.type.ts
  src/gameEventsBroker/clanEventHandler.ts
  src/gameEventsBroker/gameEventsBroker.module.ts
  src/gameEventsBroker/gameEventsHandler.ts
  src/playerTasks/decorator/period.decorator.ts
  src/playerTasks/dto/createTask.dto.ts
  src/playerTasks/enum/taskFrequency.enum.ts
  src/playerTasks/playerTasks.controller.ts
  src/playerTasks/playerTasks.json
  src/playerTasks/playerTasks.module.ts
  src/playerTasks/playerTasks.schema.ts
  src/playerTasks/playerTasks.service.ts
  src/playerTasks/type/tasks.type.ts
  src/rewarder/clanRewarder/clanRewarder.service.ts
  src/rewarder/clanRewarder/points.ts
  src/rewarder/rewarder.module.ts
  tsconfig.json
Labels: feature, PR

#429 Fix failing tests after 09.02.2025 release
  src/__tests__/clan/modules/clanCommon.ts
  src/dailyTasks/dailyTasks.module.ts
  src/rewarder/rewarder.module.ts
Labels: bug, PR

#436 Add skeleton of box module
  src/app.module.ts
  src/box/box.controller.ts
  src/box/box.module.ts
  src/box/box.service.ts
  src/box/dto/box.dto.ts
  src/box/dto/createBox.dto.ts
  src/box/dto/updateBox.dto.ts
  src/box/enum/BoxReference.enum.ts
  src/box/enum/SessionStage.enum.ts
  src/box/schemas/box.schema.ts
  src/box/schemas/groupAdmin.schema.ts
  src/box/schemas/tester.schema.ts
  src/common/enum/modelName.enum.ts
Labels: feature

#440 Feature/create claim tester account endpoints 420
  package-lock.json
  package.json
  src/box/box.controller.ts
  src/box/box.service.ts
  src/box/dto/claimAccountResponse.dto.ts
  src/main.ts
Labels: feature, PR

#443 feat(BoxService): include box_id in JWT access token payload
  src/box/box.service.ts
Labels: feature, PR

#444 Add /box POST endpoint
  src/__tests__/box/BoxCreator/createBox.test.ts
  src/__tests__/box/BoxHelper/isBoxRegistered.test.ts
  src/__tests__/box/BoxHelper/validateBox.test.ts
  src/__tests__/box/BoxService/createBox.test.ts
  src/__tests__/box/BoxService/deleteBoxReferences.test.ts
  src/__tests__/box/data/box/BoxBuilder.ts
  src/__tests__/box/data/box/CreateBoxDtoBuilder.ts
  src/__tests__/box/data/box/TesterBuilder.ts
  src/__tests__/box/data/box/UpdateBoxDtoBuilder.ts
  src/__tests__/box/data/boxBuilderFactory.ts
  src/__tests__/box/data/groupAdmin/GroupAdminBuilder.ts
  src/__tests__/box/groupAdmin/GroupAdminService/isRegisteredPassword.test.ts
  src/__tests__/box/modules/box.module.ts
  src/__tests__/box/modules/boxCommon.ts
  src/__tests__/box/util/generateClanNames.test.ts
  src/__tests__/chat/data/chat/ChatBuilder.ts
  src/__tests__/chat/data/chat/MessageBuilder.ts
  src/__tests__/chat/data/chatBuilderFactory.ts
  src/box/auth/BoxAuthHandler.ts
  src/box/auth/BoxUser.ts
  src/box/box.controller.ts
  src/box/box.module.ts
  src/box/box.service.ts
  src/box/boxCreator.ts
  src/box/dto/createBox.dto.ts
  src/box/dto/createdBox.dto.ts
  src/box/groupAdmin/groupAdmin.schema.ts
  src/box/groupAdmin/groupAdmin.service.ts
  src/box/payloads/CreatedBox.ts
  src/box/util/boxHelper.ts
  src/box/util/generateClanNames.ts
  src/chat/chat.schema.ts
  src/common/service/envHandler/enum/environment.enum.ts
  src/common/service/envHandler/envVars.ts
Labels: feature, PR

#448 Add endpoints for managing box custom daily tasks
  src/__tests__/auth/box/BoxAuthService/signIn.test.ts
  src/__tests__/auth/modules/auth.module.ts
  src/__tests__/auth/modules/authCommonModule.ts
  src/__tests__/box/BoxCreator/createBox.test.ts
  src/__tests__/box/BoxService/updateOneById.test.ts
  src/__tests__/box/auth/BoxAuthHandler/getGroupAdminToken.test.ts
  src/__tests__/box/auth/BoxAuthHandler/isGroupAdmin.test.ts
  src/__tests__/box/dailyTask/DailyTaskService/addMultiple.test.ts
  src/__tests__/box/dailyTask/DailyTaskService/addOne.test.ts
  src/__tests__/box/dailyTask/DailyTaskService/deleteOneById.test.ts
  src/__tests__/box/dailyTask/DailyTaskService/updateOneById.test.ts
  src/__tests__/box/data/box/BoxBuilder.ts
  src/__tests__/box/data/box/BoxUserBuilder.ts
  src/__tests__/box/data/boxBuilderFactory.ts
  src/__tests__/box/data/dailyTask/CreateDailyTaskBuilder.ts
  src/__tests__/box/data/dailyTask/CreatePredefinedDailyTaskDtoBuilder.ts
  src/__tests__/box/data/dailyTask/PredefinedDailyTaskBuilder.ts
  src/__tests__/box/data/dailyTask/UpdatePredefinedDailyTaskDtoBuilder.ts
  src/__tests__/box/data/groupAdmin/GroupAdminBuilder.ts
  src/__tests__/box/modules/box.module.ts
  src/__tests__/box/modules/boxCommon.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/authService.provider.ts
  src/auth/box/BoxAuthService.ts
  src/auth/constant.ts
  src/box/auth/BoxAuthHandler.ts
  src/box/auth/boxAuth.guard.ts
  src/box/auth/decorator/IsGroupAdmin.ts
  src/box/auth/decorator/groupAdmin.guard.ts
  src/box/box.controller.ts
  src/box/box.module.ts
  src/box/box.service.ts
  src/box/boxCreator.ts
  src/box/dailyTask/dailyTask.controller.ts
  src/box/dailyTask/dailyTask.service.ts
  src/box/dailyTask/dto/createPredefinedDailyTask.dto.ts
  src/box/dailyTask/dto/predefinedDailyTask.dto.ts
  src/box/dailyTask/dto/updatePredefinedDailyTask.dto.ts
  src/box/dailyTask/payloads/CreateDailyTask.ts
  src/box/dailyTask/predefinedDailyTask.schema.ts
  src/box/schemas/box.schema.ts
  src/common/decorator/param/LoggedUser.decorator.ts
  src/common/decorator/response/FormatAPIResponse.ts
  src/profile/dto/createProfile.dto.ts
Labels: feature, PR

#453 Add PasswordGenerator class to generate user readable passwords
  src/__tests__/box/modules/box.module.ts
  src/__tests__/box/modules/boxCommon.ts
  src/__tests__/box/tester/PasswordGenerator/generatePassword.test.ts
  src/box/box.module.ts
  src/box/tester/passwordGenerator.ts
Labels: feature, PR

#456 Add 102 and 203 custom character types
  src/player/customCharacter/const/CharacterBaseStats.ts
  src/player/customCharacter/enum/characterId.enum.ts
Labels: feature, PR
