Repository Alt-Org/Altzone-Server, pull requests merged in 2025-03, with the labels that each got.

#458 Endpoint for defining amount of testers in the box
  src/__tests__/box/modules/box.module.ts
  src/__tests__/box/modules/boxCommon.ts
  src/__tests__/box/tester/TesterService/addTestersToBox.test.ts
  src/__tests__/box/tester/TesterService/addTestersToClans.test.ts
  src/__tests__/box/tester/TesterService/createTesters.test.ts
  src/__tests__/box/tester/TesterService/deleteTesters.test.ts
  src/box/box.module.ts
  src/box/tester/dto/define.testers.dto.ts
  src/box/tester/tester.controller.ts
  src/box/tester/tester.service.ts
Labels: feature, PR

#460 Add new txt files with my own name.
  src/characterClass/files/jozsef.txt
Labels: feature, PR

#467 Added endpoint for deleting testing box data
  src/__tests__/box/BoxService/deleteBox.test.ts
  src/box/box.controller.ts
  src/box/box.service.ts
  src/box/tester/tester.service.ts
Labels: feature

#468 Added cron job for test sessions automating deletion
  package-lock.json
  package.json
  src/__tests__/box/BoxScheduler/resetTestingSessions.test.ts
  src/__tests__/box/modules/box.module.ts
  src/__tests__/box/modules/boxCommon.ts
  src/app.module.ts
  src/box/box.module.ts
  src/box/box.scheduler.ts
  src/box/box.service.ts
Labels: feature, PR

#471 Added /box/start POST endpoint to start testing session
  src/__tests__/box/SessionStarterService/start.test.ts
  src/__tests__/box/modules/box.module.ts
  src/__tests__/box/modules/boxCommon.ts
  src/__tests__/dailyTasks/data/dailyTaskBuilderFactory.ts
  src/__tests__/dailyTasks/data/dailyTasks/DailyTaskBuilder.ts
  src/__tests__/dailyTasks/modules/dailyTasks.module.ts
  src/__tests__/dailyTasks/modules/dailyTasksCommon.module.ts
  src/box/box.controller.ts
  src/box/box.module.ts
  src/box/dailyTask/dailyTask.service.ts
  src/box/sessionStarter/sessionStarter.service.ts
  src/dailyTasks/dailyTasks.schema.ts
  src/dailyTasks/dailyTasks.service.ts
Labels: feature, PR

#472 Refactor GET /player/:id endpoint so it has daily task data in response.
  src/__tests__/player/modules/playerCommon.module.ts
  src/player/dto/player.dto.ts
  src/player/dto/task.dto.ts
  src/player/player.controller.ts
  src/player/player.schema.ts
  src/player/player.service.ts
Labels: feature, PR

#474 Fixed bug, where player can add multiple same type custom characters to own account
  src/__tests__/player/customCharacter/CustomCharacterService/createOne.test.ts
  src/characterClass/files/jozsef.txt
  src/player/customCharacter/customCharacter.service.ts
Labels: bug

#477 Add auto generation from nest decorators setup
  package-lock.json
  package.json
  src/__tests__/common/decorator/response/FormatAPIResponse.test.ts
  src/__tests__/common/decorator/response/UniformResponse.test.ts
  src/__tests__/common/interceptor/response/FormatAPIResponseInterceptor/intercept.test.ts
  src/box/auth/decorator/groupAdmin.guard.ts
  src/common/controller/formatResponse.ts
  src/common/decorator/response/FormatAPIResponse.ts
  src/common/decorator/response/UniformResponse.ts
  src/common/interceptor/response/FormatAPIResponse.ts
  src/common/interceptor/response/Serialize.ts
  src/common/service/envHandler/envVars.ts
  src/main.ts
  src/swagger/documentSetup/introSection.ts
  src/swagger/documentSetup/swaggerDocumentOptions.ts
  src/swagger/documentSetup/swaggerUIOptions.ts
  src/swagger/swaggerDocumentBuilder.ts
  src/swagger/swaggerSetuper.ts
  src/swagger/tags/SwaggerTags.decorator.ts
  src/swagger/tags/tags.ts
Labels: feature, PR

#476 Add POST /dailyTasks/progress endpoint to update the UI tasks.
  src/__tests__/clanInventory/item/ItemHelperService/getItemSoulHomeId.test.ts
  src/__tests__/dailyTasks/uiDailyTasks/UIDailyTasksService/updateTask.test.ts
  src/__tests__/gameEventsHandler/UiDailyTaskHandler/handleUIBasicTaskUpdate.test.ts
  src/__tests__/gameEventsHandler/modules/gameEventsHandlerCommon.ts
  src/dailyTasks/dailyTasks.controller.ts
  src/dailyTasks/dto/updateUIDailyTask.dto.ts
  src/dailyTasks/uiDailyTasks/uiDailyTasks.service.ts
  src/gameEventsEmitter/payloads/UIBasicDailyTask.ts
  src/gameEventsHandler/dailyTask/uiDailyTaskHandler.ts
  src/gameEventsHandler/gameEventsHandler.module.ts
Labels: feature, PR

#481 Fix: add maxlength validation for clan name in DTOs and schema
  src/clan/clan.schema.ts
  src/clan/dto/createClan.dto.ts
  src/clan/dto/updateClan.dto.ts
Labels: change, PR

#485 Fixed endpoints exposing profile password
  src/__tests__/common/interceptor/response/SerializeInterceptor2/SerializeInterceptor2.test.ts
  src/common/decorator/response/UniformResponse.ts
  src/common/interceptor/response/SerializeInterceptor2.ts
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
Labels: bug, PR

#487 Added field to store avatar data to player
  src/__tests__/auth/AuthService/signIn.test.ts
  src/__tests__/auth/box/BoxAuthService/signIn.test.ts
  src/__tests__/auth/modules/authCommonModule.ts
  src/__tests__/box/modules/boxCommon.ts
  src/__tests__/clan/modules/clanCommon.ts
  src/__tests__/clanInventory/modules/clanInventoryCommon.ts
  src/__tests__/itemMover/modules/itemMoverCommon.module.ts
  src/__tests__/player/PlayerService/createOne.test.ts
  src/__tests__/player/PlayerService/getAll.test.ts
  src/__tests__/player/PlayerService/getPlayerById.test.ts
  src/__tests__/player/PlayerService/updateOneById.test.ts
  src/__tests__/player/data/player/createPlayerDtoBuilder.ts
  src/__tests__/player/data/player/playerBuilder.ts
  src/__tests__/player/data/player/playerDtoBuilder.ts
  src/__tests__/player/data/player/updatePlayerDtoBuilder.ts
  src/__tests__/player/modules/player.module.ts
  src/__tests__/player/modules/playerCommon.module.ts
  src/__tests__/profile/ProfileService/readOneWithCollections.test.ts
  src/__tests__/test_utils/connect-to-db.ts
  src/__tests__/test_utils/const/loggedUser.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/box/BoxAuthService.ts
  src/box/box.module.ts
  src/box/box.service.ts
  src/box/boxCreator.ts
  src/box/dto/createdBox.dto.ts
  src/box/payloads/CreatedBox.ts
  src/box/sessionStarter/sessionStarter.service.ts
  src/box/tester/tester.service.ts
  src/box/util/boxHelper.ts
  src/clan/clan.module.ts
  src/clan/clan.service.ts
  src/clan/join/join.service.ts
  src/clanInventory/clanInventory.module.ts
  src/clanInventory/item/item.controller.ts
  src/clanInventory/room/utils/room.helper.service.ts
  src/clanInventory/soulhome/utils/soulHomeHelper.service.ts
  src/common/interceptor/response/FormatAPIResponse.ts
  src/itemMover/itemMover.module.ts
  src/itemMover/itemMover.service.ts
  src/player/customCharacter/customCharacter.schema.ts
  src/player/customCharacter/customCharacter.service.ts
  src/player/decorator/validation/IsPlayerExists.decorator.ts
  src/player/dto/avatar.dto.ts
  src/player/dto/createPlayer.dto.ts
  src/player/dto/modifyAvatar.dto.ts
  src/player/dto/player.dto.ts
  src/player/dto/updatePlayer.dto.ts
  src/player/player.controller.ts
  src/player/player.module.ts
  src/player/player.service.ts
  src/player/schemas/avatar.schema.ts
  src/player/schemas/player.schema.ts
  src/profile/profile.schema.ts
Labels: feature, PR
