Repository Alt-Org/Altzone-Server, pull requests merged in 2025-05, with the labels that each got.

#541 Change player battle characters storing mechanism 517
  src/__tests__/common/decorator/validation/IsMongoIdOrNull/IsMongoIdOrNull.test.ts
  src/__tests__/player/PlayerService/createOne.test.ts
  src/__tests__/player/PlayerService/updateOneById.test.ts
  src/__tests__/player/data/player/createPlayerDtoBuilder.ts
  src/__tests__/player/data/player/playerBuilder.ts
  src/__tests__/player/data/player/playerDtoBuilder.ts
  src/__tests__/player/data/player/updatePlayerDtoBuilder.ts
  src/common/decorator/validation/IsMongoIdOrNull.decorator.ts
  src/player/dto/createPlayer.dto.ts
  src/player/dto/updatePlayer.dto.ts
Labels: change, PR

#544 Added DB transactions support
  README.md
  docker-compose.yml
  init-db-on-linux.sh
  init-db-on-windows.ps1
  mongo-update.sh
  mongo.Dockerfile
  mongod.conf
  package-lock.json
  package.json
  prod_api.Dockerfile
  prod_docker-compose.yml
  src/__tests__/clanInventory/item/ItemHelperService/getItemClanId.test.ts
  src/__tests__/clanInventory/item/ItemHelperService/getItemSoulHomeId.test.ts
  src/__tests__/common/interceptor/response/FormatAPIResponseInterceptor/intercept.test.ts
  src/__tests__/common/service/basicService/BasicService/BasicService.readOneById.test.ts
  src/__tests__/itemMover/ItemMoverService/moveItem.test.ts
  src/__tests__/itemMover/ItemMoverService/moveItems.test.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
  src/__tests__/onlinePlayers/modules/onlinePlayers.module.ts
  src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
  src/__tests__/player/PlayerService/deleteOneById.test.ts
  src/__tests__/player/PlayerService/getAll.test.ts
  src/__tests__/player/PlayerService/getPlayerById.test.ts
  src/__tests__/player/PlayerService/readOneById.test.ts
  src/__tests__/player/PlayerService/readOneWithAllCollections.test.ts
  src/__tests__/player/PlayerService/readOneWithCollections.test.ts
  src/__tests__/player/PlayerService/updatePlayerById.test.ts
  src/__tests__/profile/ProfileService/deleteOneById.test.ts
  src/__tests__/profile/ProfileService/readOneById.test.ts
  src/__tests__/profile/ProfileService/readOneWithAllCollections.test.ts
  src/__tests__/profile/ProfileService/readOneWithCollections.test.ts
  src/__tests__/test_utils/data/RequestBuilder.ts
  src/app.module.ts
  src/authorization/authorization.interceptor.ts
  src/authorization/caslAbility.factory.ts
  src/authorization/rule/joinRequestRules.ts
  src/authorization/rule/stockRules.ts
  src/authorization/util/getClan_id.ts
  src/clan/clan.controller.ts
  src/clan/join/dto/removePlayer.dto.ts
  src/common/decorator/request/AddGetQueries.decorator.ts
  src/common/interceptor/response/FormatAPIResponse.ts
  src/common/service/redis/cacheKeys.enum.ts
  src/common/service/redis/redis.module.ts
  src/common/service/redis/redis.service.ts
  src/gameEventsHandler/clanEventHandler.ts
  src/leaderboard/leaderboard.module.ts
  src/leaderboard/leaderboard.service.ts
  src/main.ts
  src/onlinePlayers/onlinePlayers.module.ts
  src/onlinePlayers/onlinePlayers.service.ts
  src/player/player.controller.ts
  src/profile/profile.service.ts
Labels: feature, PR

#554 Added swagger description for clan endpoints via decorators
  nest-cli.json
  src/__tests__/clanShop/clanShopService/buyItem.test.ts
  src/clan/clan.controller.ts
  src/clan/dto/clan.dto.ts
  src/clan/dto/clanItems.dto.ts
  src/clan/dto/clanLogo.dto.ts
  src/clan/dto/createClan.dto.ts
  src/clan/dto/updateClan.dto.ts
  src/clan/join/dto/clanItemsResponse.dto.ts
  src/clan/join/dto/join.dto.ts
  src/clan/join/dto/joinRequest.dto.ts
  src/clan/join/dto/joinResult.dto.ts
  src/clan/join/dto/removePlayer.dto.ts
  src/common/base/decorator/AddType.decorator.ts
  src/common/controller/APIError.ts
  src/common/swagger/documentSetup/introSection.ts
  src/common/swagger/documentSetup/swaggerDocumentOptions.ts
  src/common/swagger/documentSetup/swaggerUIOptions.ts
  src/common/swagger/response/ApiResponseDescription.ts
  src/common/swagger/response/errors/ApiStandardErrors.decorator.ts
  src/common/swagger/response/success/ApiSuccessResponse.decorator.ts
  src/common/swagger/response/success/metaData.ts
  src/common/swagger/swaggerDocumentBuilder.ts
  src/common/swagger/swaggerInitializer.ts
  src/common/swagger/tags/SwaggerTags.decorator.ts
  src/common/swagger/tags/tags.ts
  src/main.ts
Labels: docs, PR

#565 Added "status" field for online players
  src/__tests__/common/service/redis/mocks/RedisServiceInMemory.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
  src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
  src/common/service/redis/IRedisService.ts
  src/common/service/redis/redis.service.ts
  src/onlinePlayers/dto/InformPlayerIsOnline.dto.ts
  src/onlinePlayers/dto/onlinePlayer.dto.ts
  src/onlinePlayers/enum/OnlinePlayerStatus.ts
  src/onlinePlayers/onlinePlayers.controller.ts
  src/onlinePlayers/onlinePlayers.service.ts
  src/onlinePlayers/payload/AddOnlinePlayer.ts
  src/onlinePlayers/payload/OnlinePlayer.ts
Labels: change, PR

#566 Added filtering for /online-players GET enpoint by `status` field
  src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
  src/onlinePlayers/dto/OnlinePlayerSearchQuery.dto.ts
  src/onlinePlayers/onlinePlayers.controller.ts
  src/onlinePlayers/onlinePlayers.service.ts
Labels: change, PR

#563 Changed time to live for leaderboards to 3h
  src/leaderboard/leaderboard.service.ts
Labels: bug, PR

#568 Added /online-players/battleQueue GET endpoint to retrieve online players waiting in battle queue
  src/__tests__/common/service/redis/mocks/RedisServiceInMemory.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/getOnlinePlayerById.test.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/getOnlinePlayers.test.ts
  src/__tests__/onlinePlayers/battleQueue/BattleQueueService/getPlayerQueueNumber.test.ts
  src/__tests__/onlinePlayers/battleQueue/BattleQueueService/sortPlayersByQueueNumber.test.ts
  src/__tests__/onlinePlayers/data/onlinePlayers/AddOnlinePlayerBuilder.ts
  src/__tests__/onlinePlayers/data/onlinePlayers/OnlinePlayerBuilder.ts
  src/__tests__/onlinePlayers/data/onlinePlayersBuilderFactory.ts
  src/__tests__/onlinePlayers/modules/battleQueue.module.ts
  src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
  src/common/service/redis/cacheKeys.enum.ts
  src/leaderboard/leaderboard.controller.ts
  src/onlinePlayers/battleQueue/battleQueue.controller.ts
  src/onlinePlayers/battleQueue/battleQueue.service.ts
  src/onlinePlayers/dto/onlinePlayer.dto.ts
  src/onlinePlayers/onlinePlayers.controller.ts
  src/onlinePlayers/onlinePlayers.module.ts
  src/onlinePlayers/onlinePlayers.service.ts
  src/onlinePlayers/payload/OnlinePlayer.ts
  src/onlinePlayers/payload/additionalTypes/BattleWaitStatus.ts
Labels: feature, PR

#555 Added an endpoint to add coins to the clan
  src/__tests__/shop/buy/ClanCoinsService/addCoins.test.ts
  src/__tests__/shop/data/clanCoins/clanCoinsDtoBuilder.ts
  src/__tests__/shop/data/clanCoins/createClanCoinsDtoBuilder.ts
  src/__tests__/shop/data/clanCoinsBuilderFactory.ts
  src/__tests__/shop/modules/clanCoins.module.ts
  src/__tests__/shop/modules/clanCoinsCommon.ts
  src/app.module.ts
  src/shop/buy/clanCoins.controller.ts
  src/shop/buy/clanCoins.service.ts
  src/shop/buy/dto/clanCoins.dto.ts
  src/shop/enum/coins.enum.dto.ts
  src/shop/shop.module.ts
Labels: feature, PR

#569 Feature/add tests for statistic keeper module 406
  src/__tests__/statisticsKeeper/PlayerStatisticService/updatePlayerStatistic.test.ts
  src/__tests__/statisticsKeeper/modules/statisticsKeeper.module.ts
  src/__tests__/statisticsKeeper/modules/statisticsKeeperCommon.module.ts
  src/statisticsKeeper/playerStatisticKeeper/playerStatisticKeeper.service.ts
Labels: PR, test
