Repository Alt-Org/Altzone-Server, pull requests merged in 2025-01, with the labels that each got.

#359 Feature/add get clan leaderboard position 336
  src/clan/clan.schema.ts
  src/leaderboard/leaderboard.controller.ts
  src/leaderboard/leaderboard.service.ts
  src/player/player.schema.ts
  swagger/swagger.json
Labels: feature, PR

#360 Feature/add get clan items endpoint 345
  src/clan/clan.controller.ts
  src/clan/clan.module.ts
  src/clan/join/dto/clanItemsResponse.dto.ts
  src/common/controller/formatResponse.ts
Labels: feature, PR

#364 add swagger description for /clan/items
  swagger/swagger.json
Labels: docs, PR

#368 Bug/fix tests for clan items 365
  src/test/clan/ClanHelperService/createDefaultSoulHome.test.ts
  src/test/clan/utils/defaultValues/getRoomDefaultItems.test.ts
  src/test/clan/utils/defaultValues/getStockDefaultItems.test.ts
Labels: bug, PR

#370 Test/write tests for chat module 324
  src/test/chat/chatService/createMessage.test.ts
  src/test/chat/chatService/getChatOrThrow.test.ts
  src/test/chat/chatService/readAllMessages.test.ts
  src/test/chat/chatService/readMessageById.test.ts
  src/test/chat/data/chat/createChatDtoBuilder.ts
  src/test/chat/data/chat/createMessageDtoBuilder.ts
  src/test/chat/data/chatBuilderFactory.ts
  src/test/chat/decorator/isChatExists.test.ts
  src/test/chat/modules/chat.module.ts
  src/test/chat/modules/chatCommon.module.ts
Labels: PR, test

#383 add tests for clanInventory module
  .gitignore
  src/clanInventory/item/item.schema.ts
  src/clanInventory/room/room.service.ts
  src/clanInventory/soulhome/soulhome.service.ts
  src/test/auth/data/auth/SignInDtoBuilder.ts
  src/test/auth/data/auth/User.ts
  src/test/auth/data/clanBuilderFactory.ts
  src/test/auth/modules/auth.module.ts
  src/test/auth/modules/authCommonModule.ts
  src/test/clanInventory/data/item/ItemBuilder.ts
  src/test/clanInventory/data/item/createItemDtoBuilder.ts
  src/test/clanInventory/data/stock/CreateStockDtoBuilder.ts
  src/test/clanInventory/data/stock/StockBuilder.ts
  src/test/clanInventory/item/ItemHelperService/getItemClanId.test.ts
  src/test/clanInventory/item/ItemHelperService/getItemSoulHomeId.test.ts
  src/test/clanInventory/item/ItemService/createMany.test.ts
  src/test/clanInventory/item/ItemService/createOne.test.ts
  src/test/clanInventory/item/ItemService/deleteAllRoomItems.test.ts
  src/test/clanInventory/item/ItemService/deleteAllStockItems.test.ts
  src/test/clanInventory/item/ItemService/deleteOneById.test.ts
  src/test/clanInventory/item/ItemService/readMany.test.ts
  src/test/clanInventory/item/ItemService/readOneById.test.ts
  src/test/clanInventory/item/ItemService/updateMany.test.ts
  src/test/clanInventory/item/ItemService/updateOneById.test.ts
  src/test/clanInventory/item/decorator/validation/IsItemExists.ts/IsStockExists.test.ts
  src/test/clanInventory/item/guards/AuthGuard/canActivate.test.ts
  src/test/clanInventory/modules/item.module.ts
  src/test/clanInventory/modules/room.module.ts
  src/test/clanInventory/modules/soulhome.module.ts
  src/test/clanInventory/modules/stock.module.ts
  src/test/clanInventory/room/RoomService/activateRoomsByIds.test.ts
  src/test/clanInventory/room/RoomService/createMany.test.ts
  src/test/clanInventory/room/RoomService/createOne.test.ts
  src/test/clanInventory/room/RoomService/deleteAllSoulHomeRooms.test.ts
  src/test/clanInventory/room/RoomService/deleteOneById.test.ts
  src/test/clanInventory/room/RoomService/readAllSoulHomeRooms.test.ts
  src/test/clanInventory/room/RoomService/readOneById.test.ts
  src/test/clanInventory/room/RoomService/readOneByIdAndPlayerId.test.ts
  src/test/clanInventory/room/RoomService/readPlayerClanRooms.test.ts
  src/test/clanInventory/room/RoomService/updateOneById.test.ts
  src/test/clanInventory/room/utils/RoomHelperService/getPlayerRooms.test.ts
  src/test/clanInventory/room/utils/RoomHelperService/getPlayerSoulHome.test.ts
  src/test/clanInventory/soulhome/SoulHomeService/createOne.test.ts
  src/test/clanInventory/soulhome/SoulHomeService/deleteOneById.test.ts
  src/test/clanInventory/soulhome/SoulHomeService/readOneById.test.ts
  src/test/clanInventory/soulhome/SoulHomeService/updateOneById.test.ts
  src/test/clanInventory/soulhome/util/SoulHomeHelperService/getPlayerSoulHome.test.ts
  src/test/clanInventory/stock/StockService/createOne.test.ts
  src/test/clanInventory/stock/StockService/deleteOneById.test.ts
  src/test/clanInventory/stock/StockService/readAll.test.ts
  src/test/clanInventory/stock/StockService/readOneById.test.ts
  src/test/clanInventory/stock/StockService/updateOneById.test.ts
  src/test/clanInventory/stock/StockService/updateStockCellCount.test.ts
  src/test/clanInventory/stock/decorator/validation/IsStockExists.ts/IsStockExists.test.ts
  tsconfig.json
Labels: PR, test

#385 fix clan module tests
  src/clan/dto/createClan.dto.ts
  src/clan/dto/updateClan.dto.ts
  src/test/clan/data/clan/ClanBuilder.ts
  src/test/clan/data/clan/CreateClanDtoBuilder.ts
  src/test/clan/data/clan/UpdateClanDtoBuilder.ts
  src/test/clan/data/clan/join/JoinRequestDtoBuilder.ts
  src/test/clan/data/clan/join/RemovePlayerDtoBuilder.ts
Labels: PR, test

#387 Change/add hp field custom character 234
  src/customCharacter/customCharacter.schema.ts
  src/customCharacter/dto/createCustomCharacter.dto.ts
  src/customCharacter/dto/customCharacter.dto.ts
  src/customCharacter/dto/updateCustomCharacter.dto.ts
Labels: change, PR

#386 Change/remove custom character delete endpoint
  src/customCharacter/customCharacter.controller.ts
  src/customCharacter/customCharacter.service.ts
Labels: change, PR

#389 change CustomCharacter to use BasicService
  src/__tests__/chat/chatService/createMessage.test.ts
  src/__tests__/clan/join/JoinService/handleJoinRequest.test.ts
  src/__tests__/customCharacter/CustomCharacterService/createOne.test.ts
  src/__tests__/customCharacter/CustomCharacterService/deleteMany.test.ts
  src/__tests__/customCharacter/CustomCharacterService/readMany.test.ts
  src/__tests__/customCharacter/CustomCharacterService/readOneById.test.ts
  src/__tests__/customCharacter/CustomCharacterService/updateOneById.test.ts
  src/__tests__/customCharacter/data/customCharacter/CreateCustomCharacterDtoBuilder.ts
  src/__tests__/customCharacter/data/customCharacter/CustomCharacterBuilder.ts
  src/__tests__/customCharacter/data/customCharacter/UpdateCustomCharacterDtoBuilder.ts
  src/__tests__/customCharacter/data/customCharacterBuilderFactory.ts
  src/__tests__/customCharacter/modules/customCharacter.module.ts
  src/__tests__/customCharacter/modules/customCharacterCommon.ts
  src/__tests__/player/PlayerService/updateOneById.test.ts
  src/common/service/basicService/ServiceError.ts
  src/customCharacter/const/CharacterBaseStats.ts
  src/customCharacter/customCharacter.controller.ts
  src/customCharacter/customCharacter.module.ts
  src/customCharacter/customCharacter.schema.ts
  src/customCharacter/customCharacter.service.ts
  src/customCharacter/dto/createCustomCharacter.dto.ts
  src/customCharacter/dto/customCharacter.dto.ts
  src/customCharacter/dto/updateCustomCharacter.dto.ts
  src/customCharacter/enum/characterId.enum.ts
  src/player/player.service.ts
Labels: change, PR

#390 Add functionality to allowing manipulate only own customer characters
  src/__tests__/customCharacter/CustomCharacterService/readOne.test.ts
  src/__tests__/customCharacter/CustomCharacterService/updateOneByCondition.test.ts
  src/authorization/rule/customCharacterRules.ts
  src/customCharacter/customCharacter.controller.ts
  src/customCharacter/customCharacter.service.ts
Labels: change, PR
