Repository Alt-Org/Altzone-Server, pull requests merged in 2025-04, with the labels that each got.

#488 fix: rename prettier.config.js to prettier.config.mjs
  prettier.config.mjs
Labels: bug, PR

#489 Added unit tests for rewarder module
  src/__tests__/clan/data/clan/ClanBuilder.ts
  src/__tests__/player/data/message/MessageBuilder.ts
  src/__tests__/player/data/playerBuilderFactory.ts
  src/__tests__/rewarder/ClanRewarder/rewardClanForPlayerTask.test.ts
  src/__tests__/rewarder/PlayerRewarder/rewardForPlayerEvent.test.ts
  src/__tests__/rewarder/PlayerRewarder/rewardForPlayerTask.test.ts
  src/__tests__/rewarder/modules/clanRewarder.module.ts
  src/__tests__/rewarder/modules/rewarderCommon.ts
  src/rewarder/clanRewarder/clanRewarder.service.ts
  src/rewarder/playerRewarder/playerRewarder.service.ts
Labels: PR, test

#482 Added logic and endpoints for tracking the number of online players.
  src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
  src/__tests__/onlinePlayers/modules/onlinePlayers.module.ts
  src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
  src/__tests__/onlinePlayers/service/getAllOnlinePlayers.test.ts
  src/app.module.ts
  src/common/enum/cacheKeys.enum.ts
  src/leaderboard/leaderboard.service.ts
  src/onlinePlayers/onlinePlayers.controller.ts
  src/onlinePlayers/onlinePlayers.module.ts
  src/onlinePlayers/onlinePlayers.service.ts
Labels: feature, PR

#495 Fixed the tests for onlinePlayers service
  src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
  src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
  src/__tests__/onlinePlayers/service/getAllOnlinePlayers.test.ts
Labels: bug, PR

#503 Created clan shop items list
  src/__tests__/clan/ClanHelperService/createDefaultSoulHome.test.ts
  src/__tests__/clan/utils/defaultValues/getRoomDefaultItems.test.ts
  src/__tests__/clanInventory/data/item/ItemBuilder.ts
  src/__tests__/clanInventory/data/item/createItemDtoBuilder.ts
  src/__tests__/clanInventory/item/ItemService/readMany.test.ts
  src/__tests__/clanInventory/item/ItemService/updateMany.test.ts
  src/__tests__/itemMover/ItemMoverService/moveItem.test.ts
  src/__tests__/itemMover/ItemMoverService/moveItems.test.ts
  src/__tests__/itemMover/ItemMoverService/stealItems.test.ts
  src/clan/utils/defaultValues/items.ts
  src/clanInventory/item/const/itemProperties.ts
  src/clanInventory/item/dto/createItem.dto.ts
  src/clanInventory/item/dto/item.dto.ts
  src/clanInventory/item/enum/itemName.enum.ts
  src/clanInventory/item/enum/material.enum.ts
  src/clanInventory/item/enum/rarity.enum.ts
  src/clanInventory/item/item.schema.ts
  src/fleaMarket/dto/createFleaMarketItem.dto.ts
  src/fleaMarket/dto/fleaMarketItem.dto.ts
  src/fleaMarket/fleaMarketItem.schema.ts
Labels: feature, PR

#508 Added clan shop items rotating machanism
  src/__tests__/clanShop/ClanShopScheduler/getRandomItems.test.ts
  src/__tests__/clanShop/ClanShopScheduler/resetShopItems.test.ts
  src/__tests__/clanShop/modules/clanShop.module.ts
  src/__tests__/clanShop/modules/clanShopCommon.module.ts
  src/app.module.ts
  src/clanShop/clanShop.module.ts
  src/clanShop/clanShop.scheduler.ts
Labels: feature, PR

#509 Added endpoint for getting clan shop items
  src/clanShop/clanShop.controller.ts
  src/clanShop/clanShop.module.ts
Labels: feature, PR

#507 Fixed flea market items using an old items schema
  src/clanInventory/item/item.schema.ts
  src/fleaMarket/dto/createFleaMarketItem.dto.ts
  src/fleaMarket/dto/fleaMarketItem.dto.ts
  src/fleaMarket/fleaMarketHelper.service.ts
  src/fleaMarket/fleaMarketItem.schema.ts
Labels: bug, PR

#511 Added roles field to clan data
  src/__tests__/clan/data/clan/ClanBuilder.ts
  src/__tests__/player/PlayerService/getAll.test.ts
  src/__tests__/player/PlayerService/getPlayerById.test.ts
  src/__tests__/player/PlayerService/readOneWithCollections.test.ts
  src/clan/clan.schema.ts
  src/clan/dto/clan.dto.ts
  src/clan/role/ClanRole.schema.ts
  src/clan/role/dto/clanRole.dto.ts
  src/clan/role/enum/clanBasicRight.enum.ts
  src/clan/role/enum/clanRoleType.enum.ts
  src/clan/role/initializationClanRoles.ts
Labels: feature, PR

#514 Set player_id field to null by default for daily tasks
  src/box/sessionStarter/sessionStarter.service.ts
  src/clan/role/ClanRole.schema.ts
  src/clan/role/initializationClanRoles.ts
  src/dailyTasks/dailyTasks.schema.ts
Labels: bug, PR

#515 Added clan role information to player data
  src/__tests__/auth/AuthService/signIn.test.ts
  src/__tests__/auth/box/BoxAuthService/signIn.test.ts
  src/__tests__/auth/modules/authCommonModule.ts
  src/__tests__/box/BoxCreator/createBox.test.ts
  src/__tests__/clan/ClanService/createOne.test.ts
  src/__tests__/clan/ClanService/readOneById.test.ts
  src/__tests__/clan/data/clan/ClanBuilder.ts
  src/__tests__/clan/join/JoinService/handleJoinRequest.test.ts
  src/__tests__/player/data/player/playerBuilder.ts
  src/__tests__/test_utils/const/loggedUser.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/box/BoxAuthService.ts
  src/authorization/rule/playerRules.ts
  src/clan/clan.service.ts
  src/clan/join/join.service.ts
  src/player/dto/player.dto.ts
  src/player/schemas/player.schema.ts
Labels: feature, PR

#519 Test/add tests for voting module 407
  src/__tests__/common/service/notificator/mocks/createMockMqttClient.ts
  src/__tests__/fleaMarket/data/fleaMarket/CreateFleaMarketItemDtoBuilder.ts
  src/__tests__/fleaMarket/data/fleaMarket/FleaMarketItemBuilder.ts
  src/__tests__/fleaMarket/data/fleaMarket/FleaMarketItemDtoBuilder.ts
  src/__tests__/fleaMarket/data/fleaMarketBuilderFactory.ts
  src/__tests__/fleaMarket/modules/fleaMarketCommon.ts
  src/__tests__/fleaMarket/modules/fleaMarketModule.ts
  src/__tests__/voting/VotingNotifier/newVoting.test.ts
  src/__tests__/voting/VotingNotifier/votingCompleted.test.ts
  src/__tests__/voting/VotingNotifier/votingError.test.ts
  src/__tests__/voting/VotingNotifier/votingUpdated.test.ts
  src/__tests__/voting/VotingService/addVote.test.ts
  src/__tests__/voting/VotingService/checkVotingSuccess.test.ts
  src/__tests__/voting/VotingService/createOne.test.ts
  src/__tests__/voting/VotingService/getClanVotings.test.ts
  src/__tests__/voting/VotingService/startItemVoting.test.ts
  src/__tests__/voting/VotingService/validatePermission.test.ts
  src/__tests__/voting/data/VotingBuilderFactory.ts
  src/__tests__/voting/data/organizer/OrganizerBuilder.ts
  src/__tests__/voting/data/voting/VoteBuilder.ts
  src/__tests__/voting/data/voting/VotingDtoBuilder.ts
  src/__tests__/voting/data/voting/createStartItemVotingParamsDtoBuilder.ts
  src/__tests__/voting/data/voting/createVotingDtoBuilder.ts
  src/__tests__/voting/modules/voting.module.ts
  src/__tests__/voting/modules/votingCommon.module.ts
Labels: PR, test

#520 Added endpoint for clan named roles creation
  src/__tests__/auth/data/authBuilderFactory.ts
  src/__tests__/clan/data/clanBuilderFactory.ts
  src/__tests__/clan/data/role/ClanRoleBuilder.ts
  src/__tests__/clan/data/role/CreateClanRoleDtoBuilder.ts
  src/__tests__/clan/modules/clan.module.ts
  src/__tests__/clan/modules/clanCommon.ts
  src/__tests__/clan/role/ClanRoleService/ClanRoleService.createOne.test.ts
  src/__tests__/clan/role/clanRoleUtils/isRoleDuplicate.test.ts
  src/__tests__/clan/role/clanRoleUtils/isRoleNameExists.test.ts
  src/__tests__/clan/role/decorator/guard/HasClanRightsGuard/canActivate.test.ts
  src/__tests__/clan/role/decorator/validation/IsRoleRights.decorator/IsRoleRights.test.ts
  src/__tests__/clan/role/decorator/validation/validators/areRoleRightsValid.test.ts
  src/__tests__/common/exceptionFilter/APIErrorFilter/APIErrorFilter.catch.test.ts
  src/authorization/caslAbility.factory.ts
  src/authorization/rule/clanRules.ts
  src/authorization/type/RulesSetter.type.ts
  src/clan/clan.module.ts
  src/clan/role/ClanRole.schema.ts
  src/clan/role/clanRole.controller.ts
  src/clan/role/clanRole.service.ts
  src/clan/role/clanRoleUtils.ts
  src/clan/role/const/validation.ts
  src/clan/role/decorator/guard/HasClanRights.ts
  src/clan/role/decorator/validation/IsRoleRights.decorator.ts
  src/clan/role/decorator/validation/validators.ts
  src/clan/role/dto/createClanRole.dto.ts
  src/common/exceptionFilter/APIErrorFilter.ts
  src/common/guard/clanId.guard.ts
Labels: feature, PR

#522 Added endpoint to delete named role from clan
  src/__tests__/clan/role/ClanRoleService/ClanRoleService.deleteOneById.test.ts
  src/clan/role/clanRole.controller.ts
  src/clan/role/clanRole.service.ts
Labels: feature, PR

#523 Add buy item from shop endpoint and refactor voting queue logic.
  src/__tests__/clanShop/clanShopService/buyItem.test.ts
  src/__tests__/clanShop/clanShopService/checkVotingOnExpire.test.ts
  src/__tests__/clanShop/modules/clanShop.module.ts
  src/__tests__/clanShop/modules/clanShopCommon.module.ts
  src/__tests__/fleaMarket/modules/fleaMarketCommon.ts
  src/__tests__/voting/data/voting/VotingDtoBuilder.ts
  src/clanShop/clanShop.controller.ts
  src/clanShop/clanShop.module.ts
  src/clanShop/clanShop.service.ts
  src/clanShop/clanShopVoting.processor.ts
  src/fleaMarket/fleaMarket.module.ts
  src/fleaMarket/fleaMarket.service.ts
  src/fleaMarket/fleaMarketVoting.processor.ts
  src/fleaMarket/types/votingQueueParams.type.ts
  src/fleaMarket/voting.queue.ts
  src/voting/dto/createVoting.dto.ts
  src/voting/dto/voting.dto.ts
  src/voting/enum/VotingQueue.enum.ts
  src/voting/schemas/voting.schema.ts
  src/voting/type/notifierPayload.type.ts
  src/voting/type/startItemVoting.type.ts
  src/voting/voting.module.ts
  src/voting/voting.notifier.ts
  src/voting/voting.queue.ts
  src/voting/voting.service.ts
Labels: feature, PR

#528 Added endpoint for updating clan role
  src/__tests__/clan/data/clanBuilderFactory.ts
  src/__tests__/clan/data/role/UpdateClanRoleDtoBuilder.ts
  src/__tests__/clan/role/ClanRoleService/ClanRoleService.deleteOneById.test.ts
  src/__tests__/clan/role/ClanRoleService/ClanRoleService.updateOneById.test.ts
  src/clan/role/clanRole.controller.ts
  src/clan/role/clanRole.service.ts
  src/clan/role/dto/updateClanRole.dto.ts
Labels: feature, PR

#529 The online players now returns an object containing name and id
  src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
  src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
  src/__tests__/onlinePlayers/modules/onlinePlayers.module.ts
  src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
  src/onlinePlayers/onlinePlayers.controller.ts
  src/onlinePlayers/onlinePlayers.module.ts
  src/onlinePlayers/onlinePlayers.service.ts
Labels: change, PR

#531 Added /clan/role/set PUT endpoint for setting a role for a clan member
  src/__tests__/clan/data/clanBuilderFactory.ts
  src/__tests__/clan/data/role/SetClanRoleBuilder.ts
  src/__tests__/clan/role/ClanRoleService/ClanRoleService.setRoleToPlayer.test.ts
  src/__tests__/clan/role/decorator/guard/HasClanRightsGuard/canActivate.test.ts
  src/__tests__/player/data/player/playerBuilder.ts
  src/clan/role/clanRole.controller.ts
  src/clan/role/clanRole.service.ts
  src/clan/role/decorator/guard/HasClanRights.ts
  src/clan/role/dto/setClanRole.dto.ts
  src/common/controller/APIError.ts
  src/common/exceptionFilter/APIErrorFilter.ts
Labels: feature, PR

#533 Fixed a bug where /clan GET endpoint does not return pagination data
  src/clan/clan.controller.ts
Labels: bug, PR

#534 Feature add clan logo to player leaderboard data
  src/leaderboard/dto/leaderboardPlayer.dto.ts
  src/leaderboard/leaderboard.controller.ts
  src/leaderboard/leaderboard.service.ts
Labels: feature, PR

#538 Fixed wrong response types retunred from endpoints
  src/common/interceptor/response/Send204OnEmptyRes.ts
  src/profile/profile.controller.ts
Labels: bug, PR

#537 Added edit "shop" permission validation for all related endpoints
  src/clanShop/clanShop.controller.ts
  src/clanShop/clanShop.module.ts
  src/fleaMarket/fleaMarket.controller.ts
  src/fleaMarket/fleaMarket.module.ts
Labels: feature, PR

#536 Added permission validation for edit clan data right for /clan PUT endpoint
  src/clan/clan.controller.ts
Labels: feature, PR

#535 Added edit soul home permission validation for /item PUT endpoint
  src/clanInventory/item/item.controller.ts
Labels: feature, PR
