Repository Alt-Org/Altzone-Server, pull requests merged in 2025-07, with the labels that each got.

#595 Added tests for flea market module
  src/__tests__/clan/data/clan/ClanDtoBuilder.ts
  src/__tests__/clan/data/clanBuilderFactory.ts
  src/__tests__/clanInventory/data/clanInventoryBuilderFactory.ts
  src/__tests__/clanInventory/data/item/ItemDtoBuilder.ts
  src/__tests__/common/MongooseSession/CreateMockSession.ts
  src/__tests__/fleaMarket/FleaMarketHelperService/fleaMarketItemToCreateItemDto.test.ts
  src/__tests__/fleaMarket/FleaMarketHelperService/itemToCreateFleaMarketItem.test.ts
  src/__tests__/fleaMarket/FleaMarketService/checkVotingOnExpire.test.ts
  src/__tests__/fleaMarket/FleaMarketService/createOne.test.ts
  src/__tests__/fleaMarket/FleaMarketService/getClanId.test.ts
  src/__tests__/fleaMarket/FleaMarketService/handleBuyItem.test.ts
  src/__tests__/fleaMarket/FleaMarketService/handleSellItem.test.ts
  src/__tests__/fleaMarket/FleaMarketService/readMany.test.ts
  src/__tests__/fleaMarket/FleaMarketService/readOneById.test.ts
  src/__tests__/fleaMarket/FleaMarketVotingProcessor/process.test.ts
  src/__tests__/fleaMarket/modules/fleaMarketCommon.ts
  src/__tests__/fleaMarket/modules/fleaMarketModule.ts
  src/__tests__/voting/VotingQueue/addVotingCheckJob.test.ts
  src/__tests__/voting/modules/voting.module.ts
  src/fleaMarket/fleaMarket.service.ts
Labels: PR, test

#596 Change claiming tester account logic
  src/__tests__/auth/box/BoxAuthService/signIn.test.ts
  src/__tests__/box/BoxHelper/validateBox.test.ts
  src/__tests__/box/BoxScheduler/resetTestingSessions.test.ts
  src/__tests__/box/BoxService/createBox.test.ts
  src/__tests__/box/BoxService/deleteBox.test.ts
  src/__tests__/box/BoxService/deleteBoxReferences.test.ts
  src/__tests__/box/SessionStarterService/start.test.ts
  src/__tests__/box/UniqueFieldGenerator/generateUniqueFieldValue.test.ts
  src/__tests__/box/accountClaimer/AccountClaimerService/claimAccount.test.ts
  src/__tests__/box/accountClaimer/TesterAccountService/addTesterToClan.test.ts
  src/__tests__/box/accountClaimer/TesterAccountService/createTester.test.ts
  src/__tests__/box/data/box/BoxBuilder.ts
  src/__tests__/box/data/box/TesterBuilder.ts
  src/__tests__/box/data/box/UpdateBoxDtoBuilder.ts
  src/__tests__/box/modules/box.module.ts
  src/__tests__/box/modules/boxCommon.ts
  src/__tests__/box/tester/TesterService/addTestersToBox.test.ts
  src/__tests__/box/tester/TesterService/addTestersToClans.test.ts
  src/__tests__/box/tester/TesterService/createTesters.test.ts
  src/__tests__/box/tester/TesterService/deleteTesters.test.ts
  src/__tests__/common/function/PasswordGenerator/generatePassword.test.ts
  src/__tests__/test_utils/add-custom-matchers.ts
  src/__tests__/test_utils/jest.matchers.d.ts
  src/__tests__/test_utils/matchers/serviceError/array/toContainSE_NOT_AUTHORIZED.ts
  src/__tests__/test_utils/matchers/serviceError/individual/toBeSE_NOT_AUTHORIZED.ts
  src/__tests__/test_utils/test/matchers/serviceError/array/toContainSE_NOT_AUTHORIZED.test.ts
  src/__tests__/test_utils/test/matchers/serviceError/individual/toBeSE_NOT_AUTHORIZED.test.ts
  src/auth/box/BoxAuthService.ts
  src/box/accountClaimer/accountClaimer.controller.ts
  src/box/accountClaimer/accountClaimer.service.ts
  src/box/accountClaimer/dto/claimAccount.dto.ts
  src/box/accountClaimer/dto/claimedAccount.dto.ts
  src/box/accountClaimer/payloads/claimedAccount.ts
  src/box/accountClaimer/payloads/tester.ts
  src/box/accountClaimer/testerAccount.service.ts
  src/box/box.controller.ts
  src/box/box.module.ts
  src/box/box.service.ts
  src/box/dto/box.dto.ts
  src/box/dto/updateBox.dto.ts
  src/box/schemas/box.schema.ts
  src/box/schemas/tester.schema.ts
  src/box/tester/dto/define.testers.dto.ts
  src/box/tester/tester.controller.ts
  src/box/tester/tester.service.ts
  src/box/util/UniqueFieldGenerator.ts
  src/box/util/boxHelper.ts
  src/common/service/basicService/SEReason.ts
Labels: change, PR

#601 Feature/add test session config functionality 581
  src/__tests__/box/BoxCreator/createBox.test.ts
  src/__tests__/box/BoxHelper/isBoxRegistered.test.ts
  src/__tests__/box/BoxHelper/validateBox.test.ts
  src/__tests__/box/BoxScheduler/resetTestingSessions.test.ts
  src/__tests__/box/BoxService/createBox.test.ts
  src/__tests__/box/BoxService/deleteBox.test.ts
  src/__tests__/box/BoxService/deleteBoxReferences.test.ts
  src/__tests__/box/SessionStarterService/start.test.ts
  src/__tests__/box/accountClaimer/AccountClaimerService/claimAccount.test.ts
  src/__tests__/box/data/box/BoxBuilder.ts
  src/__tests__/box/data/box/UpdateBoxDtoBuilder.ts
  src/box/accountClaimer/accountClaimer.service.ts
  src/box/box.controller.ts
  src/box/box.service.ts
  src/box/dto/clanToCreate.dto.ts
  src/box/dto/configureBox.dto.ts
  src/box/dto/tester.dto.ts
  src/box/dto/updateBox.dto.ts
  src/box/schemas/ClanToCreate.schema.ts
  src/box/schemas/box.schema.ts
  src/box/sessionStarter/sessionStarter.service.ts
Labels: feature, PR

#603 Added a way to save game feedback during testing sessions
  src/__tests__/feedback/FeedbackService/createOne.test.ts
  src/__tests__/feedback/data/feedback/CreateFeedbackBuilder.ts
  src/__tests__/feedback/data/feedback/CreateFeedbackDtoBuilder.ts
  src/__tests__/feedback/data/feedbackBuilderFactory.ts
  src/__tests__/feedback/modules/feedback.module.ts
  src/__tests__/feedback/modules/feedbackCommon.ts
  src/app.module.ts
  src/box/box.controller.ts
  src/common/enum/modelName.enum.ts
  src/common/swagger/tags/tags.ts
  src/feedback/dto/createFeedback.dto.ts
  src/feedback/dto/feedback.dto.ts
  src/feedback/feedback.controller.ts
  src/feedback/feedback.module.ts
  src/feedback/feedback.schema.ts
  src/feedback/feedback.service.ts
  src/feedback/payloads/createFeedback.ts
Labels: feature, PR

#606 Added group admin creation endpoint
  README.md
  src/box/box.controller.ts
  src/box/groupAdmin/dto/createGroupAdmin.dto.ts
Labels: feature, PR

#607 Added default testing box settings
  src/__tests__/box/SessionStarterService/start.test.ts
  src/__tests__/box/modules/boxCommon.ts
  src/__tests__/box/util/generateClanNames.test.ts
  src/box/accountClaimer/accountClaimer.service.ts
  src/box/accountClaimer/testerAccount.service.ts
  src/box/box.module.ts
  src/box/boxCreator.ts
  src/box/dailyTask/defaultPredefinedDailyTasks.ts
  src/box/schemas/box.schema.ts
  src/box/sessionStarter/sessionStarter.service.ts
  src/box/util/generateClanNames.ts
  src/box/util/generateRandomClanName.ts
  src/clan/clan.service.ts
  src/clan/dto/createClan.dto.ts
  src/clan/utils/clanHelper.service.ts
  src/clanInventory/stock/dto/createStock.dto.ts
  src/profile/profile.service.ts
Labels: change, PR
