Repository Alt-Org/Altzone-Server, pull requests merged in 2025-08, with the labels that each got.

#619 Added clan stalls for flea market items
  src/__tests__/clan/data/clan/ClanBuilder.ts
  src/__tests__/clan/data/clan/stall/AdPosterBuilder.ts
  src/__tests__/clan/data/clan/stall/StallBuilder.ts
  src/__tests__/clan/data/clanBuilderFactory.ts
  src/__tests__/fleaMarket/modules/fleaMarketCommon.ts
  src/__tests__/fleaMarket/modules/fleaMarketModule.ts
  src/__tests__/fleaMarket/stall/StallService/readAll.test.ts
  src/__tests__/fleaMarket/stall/StallService/readOneByClanId.test.ts
  src/clan/clan.schema.ts
  src/clan/dto/clan.dto.ts
  src/clan/dto/createClan.dto.ts
  src/clan/dto/stall.dto.ts
  src/clan/dto/updateClan.dto.ts
  src/clan/stall/stall.schema.ts
  src/common/enum/modelName.enum.ts
  src/common/swagger/tags/tags.ts
  src/fleaMarket/fleaMarket.module.ts
  src/fleaMarket/stall/dto/stallResponse.dto.ts
  src/fleaMarket/stall/stall.controller.ts
  src/fleaMarket/stall/stall.service.ts
Labels: feature, PR

#621 Add buy extra stall slot endpoint
  src/__tests__/box/accountClaimer/TesterAccountService/createTester.test.ts
  src/__tests__/fleaMarket/stall/StallService/buyStallSlot.test.ts
  src/auth/auth.controller.ts
  src/auth/box/BoxAuthService.ts
  src/box/accountClaimer/accountClaimer.service.ts
  src/box/accountClaimer/testerAccount.service.ts
  src/clan/clan.schema.ts
  src/clan/defaultValues/stall.ts
  src/fleaMarket/stall/dto/buyStallSlot.dto.ts
  src/fleaMarket/stall/stall.controller.ts
  src/fleaMarket/stall/stall.service.ts
Labels: feature, PR

#624 Added a selling price for selling items votings
  src/__tests__/fleaMarket/FleaMarketService/handleSellItem.test.ts
  src/__tests__/fleaMarket/data/fleaMarket/SellFleaMarketItemDtoBuilder.ts
  src/__tests__/fleaMarket/data/fleaMarketBuilderFactory.ts
  src/fleaMarket/dto/sellFleaMarketItem.dto.ts
  src/fleaMarket/fleaMarket.controller.ts
  src/fleaMarket/fleaMarket.service.ts
Labels: change, PR

#625 Refactored voting schemas
  src/__tests__/box/BoxService/deleteBox.test.ts
  src/__tests__/box/BoxService/reset.test.ts
  src/__tests__/clan/role/ClanRoleService/ClanRoleService.checkVotingOnExpire.test.ts
  src/__tests__/clanShop/clanShopService/checkVotingOnExpire.test.ts
  src/__tests__/fleaMarket/FleaMarketService/checkVotingOnExpire.test.ts
  src/__tests__/fleaMarket/FleaMarketService/handleBuyItem.test.ts
  src/__tests__/fleaMarket/FleaMarketService/handleSellItem.test.ts
  src/__tests__/fleaMarket/FleaMarketVotingProcessor/process.test.ts
  src/__tests__/voting/VotingNotifier/newVoting.test.ts
  src/__tests__/voting/VotingNotifier/votingCompleted.test.ts
  src/__tests__/voting/VotingNotifier/votingError.test.ts
  src/__tests__/voting/VotingNotifier/votingUpdated.test.ts
  src/__tests__/voting/VotingQueue/addVotingCheckJob.test.ts
  src/__tests__/voting/VotingService/addVote.test.ts
  src/__tests__/voting/VotingService/checkVotingSuccess.test.ts
  src/__tests__/voting/VotingService/createOne.test.ts
  src/__tests__/voting/VotingService/getClanVotings.test.ts
  src/__tests__/voting/VotingService/startItemVoting.test.ts
  src/__tests__/voting/VotingService/validatePermission.test.ts
  src/__tests__/voting/data/voting/FleaMarketItemVotingBuilder.ts
  src/__tests__/voting/data/voting/VotingBuilder.ts
  src/__tests__/voting/data/voting/VotingBuilderFactory.ts
  src/__tests__/voting/data/voting/buyClanShopItemVotingBuilder.ts
  src/__tests__/voting/data/voting/setClanRoleVotingBuilder.ts
  src/__tests__/voting/modules/votingCommon.module.ts
  src/voting/schemas/buyShopItem.schema.ts
  src/voting/schemas/fleamarketItemVoting.schema.ts
  src/voting/schemas/setClanRole.schema.ts
  src/voting/schemas/setClanRoleVoting.schema.ts
  src/voting/schemas/voting.schema.ts
  src/voting/voting.module.ts
  src/voting/voting.service.ts
Labels: change, PR

#627 Fixed bug with flea market selling endpoint can change the stock item price
  src/__tests__/fleaMarket/FleaMarketService/handleSellItem.test.ts
  src/__tests__/fleaMarket/modules/fleaMarketCommon.ts
  src/__tests__/voting/data/voting/FleaMarketItemVotingBuilder.ts
  src/__tests__/voting/data/voting/VotingDtoBuilder.ts
  src/fleaMarket/fleaMarket.module.ts
  src/fleaMarket/fleaMarket.service.ts
  src/voting/dto/voting.dto.ts
  src/voting/schemas/fleamarketItemVoting.schema.ts
Labels: bug, PR
